services:
  keycloak:
    image: quay.io/keycloak/keycloak
    command: start-dev
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_DATABASE: ksht_database  
      KC_DB_USERNAME: username
      KC_DB_PASSWORD: password
      KC_DB_SCHEMA: public 
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8890:8080"
    depends_on:
      - postgres
    networks:
      - ksht_network
  postgres:
    image: postgres
    command: postgres -c 'max_connections=200'
    volumes:
      - pgdata:/var/lib/postgresql/data 
    environment:
      POSTGRES_DB: ksht_database
      POSTGRES_USERNAME: username
      POSTGRES_PASSWORD: password
    ports:
      - "5436:5432"
    networks:
      - ksht_network

volumes:
  pgdata:

networks:
  ksht_network:
    driver: bridge