services:

  fastapi_container:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8009:80"
    environment:
      - DATABASE_URL=postgresql://username:password@postgres_container:5432/ksht_database 
    depends_on:
      - postgres_container
    networks:
      - ksht_network
    platform: linux/amd64

  keycloak_container:
    image: quay.io/keycloak/keycloak
    command: start-dev
    environment:
      KC_DB: postgres
      KC_DB_URL_DATABASE: ksht_database
      KC_DB_USERNAME: username 
      KC_DB_PASSWORD: password 
      KC_DB_URL_HOST: postgres_container  
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8890:8080"
    depends_on:
      - postgres_container
    networks:
      - ksht_network
  
  postgres_container:
    image: postgres
    restart: always
    volumes: 
      - ksht_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ksht_database
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    networks:
      - ksht_network

networks:
  ksht_network:
    driver: bridge

volumes:
  ksht_volume: